[package]
name = "inverter"
version = "0.1.0"
authors = ["Lluís <lluiscab@gmail.com>"]
edition = "2018"

[dependencies]
crc-any = "2.3.4"
libc = "0.2.72"
tokio = { version = "0.2.21", features = ["full"] }

[dev-dependencies]
futures = "0.3.5"
futures_ringbuf = { version = "0.2.1", features = ["tokio"] }
